// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pbkit/interface-pingpong-server/enum.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Pbkit_Enum_AWESOME: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case bC // = 0
  case eCD // = 1
  case eF // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .bC
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .bC
    case 1: self = .eCD
    case 2: self = .eF
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .bC: return 0
    case .eCD: return 1
    case .eF: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Pbkit_Enum_AWESOME: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Pbkit_Enum_AWESOME] = [
    .bC,
    .eCD,
    .eF,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Pbkit_Enum_AWESOME: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Pbkit_Enum_AWESOME: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "A_WE_SOME_B_C"),
    1: .same(proto: "AWESOMEE_C_D"),
    2: .same(proto: "AWESOME_E_F"),
  ]
}
