name: Publish to NPM
on:
  release:
    types: [released]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run --unstable -A cli/pb/entrypoint.ts vendor install
      - run: deno run --unstable -A scripts/build-npm-packages/entrypoint.ts
      - run: npm publish
        working-directory: tmp/npm/pbkit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
        working-directory: tmp/npm/runtime
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
        working-directory: tmp/npm/pb-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
